apiVersion: v1
kind: Service
metadata:
  name: "manual-inject"
spec:
  type: ClusterIP
  selector:
    service: manual-inject
  ports:
    - name: http
      port: 80
      # This port is not defined in k8s/echo-manual-inject-deploy.yaml because it will be the port used by the manually added traffic-agent
      targetPort: http
